version: '3.5'

services:
  client:
    build: 
      context: "./client"
      args:
        - 'VITE_API_URL=${VITE_API_URL}'
    image: fta2024-client
    container_name: fta2024-client
    ports:
      - '${CLIENT_PORT}:80'

  server:
    build: "./server"
    image: fta2024-server
    container_name: fta2024-server
    environment:
      - 'API_PORT=${API_PORT}'
      - 'API_KEY=${API_KEY}'
      - 'REDIS_PORT=${REDIS_PORT}'
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    ports:
      - '${API_PORT}:${API_PORT}'

  redis:
    restart: always
    image: redis:7.0
    container_name: fta2024-redis
    command: 'redis-server --requirepass ${REDIS_PASSWORD}'
    ports:
      - '${REDIS_PORT}:6379'